# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under t he License.

version: '3.8'
services:
  api:
    image: freakchicken/db-api:3.2.1
    build:
      context: ../..
      args:
        - VERSION=3.2.1
    command: ${RUN_COMMAND}
    ports:
      - 8521:8521
      - 8520:8520
    environment:
      - TZ=Asia/Shanghai
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_META_DB_URL="jdbc:mysql://192.168.111.24:23306/dbapi?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8"
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_META_DB_USERNAME=root
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_META_DB_PASSWORD=123456
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_META_DB_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_ACCESS_LOG_DB_USERNAME=root
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_ACCESS_LOG_DB_PASSWORD=123456
#      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_ACCESS_LOG_DB_URL="jdbc:mysql://192.168.111.24:23306/dbapi?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8"
#      - spring.datasource.dynamic.datasource.meta-db.driver-class-name=com.mysql.cj.jdbc.Driver
#      - spring.datasource.dynamic.datasource.meta-db.url=jdbc:mysql://192.168.111.24:23306/dbapi?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#      - spring.datasource.dynamic.datasource.meta-db.username=root
#      - spring.datasource.dynamic.datasource.meta-db.password=123456
    volumes:
      - ./runtime/dbapi/conf/application.properties:/opt/dbapi-3.2.1/conf/application.properties
#      - ./runtime/dbapi/conf/application-standalone.properties:/opt/dbapi-3.2.1/conf/application-standalone.properties
    privileged: true
    restart: unless-stopped
    networks:
      - dbapi

  # 平台Web程序
  web:
    # 总是重新启动容器：如果容器崩溃、停止或发生任何错误，Docker将尝试自动重新启动它
    restart: always
    # 镜像名称，镜像版本不推荐使用 last est，推荐指定固定版本
    image: nginx:1.21.3
    # 容器名称，xxx为项目名称缩写，可以自主替换
    container_name: dbapi-web
    volumes:
      # 挂载Web应用程序目录，用于传递应用程序在容器中运行
#      - ./runtime/web/html:/usr/share/nginx/html
      - ./dbapi-ui/dist:/usr/share/nginx/html
      - ./runtime/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./runtime/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '9101:80'
    networks:
      # 连接到名为network-xxx的网络，xxx为项目名称缩写，可以自主替换
      - dbapi
      # 工作负载名称，可用于容器内部访问，类似于短域名


networks:
  dbapi:
    driver: bridge
